%Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
%
%Triangle moduleTn=n(n+1)/24 module1, 3, 6, 10, 15, ...
%Pentagonal modulePn=n(3n−1)/24 module1, 5, 12, 22, 35, ...
%Hexagonal moduleHn=n(2n−1)module module1, 6, 15, 28, 45, ...
%It can be verified that T285 = P165 = H143 = 40755.
%
%Find the next triangle number that is also pentagonal and hexagonal.

-module(p045).
-export([timesolve/0, solve/0]).

timesolve() -> timer:tc(p045, solve, []).

solve() ->
    recurseup(40756).

recurseup(N) ->
    case eulermath:istri(N) andalso eulermath:ispent(N) andalso eulermath:ishex(N) of 
        true -> N;
        false -> recurseup(N+1)
    end.

