%Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers
%are:
%
%1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
%
%It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not
%pentagonal.
%
%Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal
%and D = |Pk − Pj| is minimised; what is the value of D?
%
%
%The assumption I made was that, after noticing the gaps between the pentagonals are growing, that
%if a pair I J checked out, then some other pair later X Y must have had a larger difference. This
%is because of the vagueness of the question "the pair of ALL pentagnol numbers (infinite set) with
%the minimum difference". I assumed the pair {I,J} with the lowest I must be it (or else the problem
%would have been too open ended). 
%
%
-module(p044).
-export([timesolve/0, solve/0]).

timesolve() -> timer:tc(p044, solve, []).

solve() ->
    T = 10000,
    D = dict:new(),
    loop(1,2,storepenta(1, T, D)).

loop(0, J, D) -> loop(J, J+1, D);
loop(I, J, D) ->
    PI = penta(I),
    PJ = penta(J),
    Works = check_pair(PI,PJ,D),
    case Works of 
        true -> PJ-PI;
        _ -> loop(I-1, J,D)
    end.

storepenta(P, Target, D) ->
    if P > Target -> D;
    true ->
        I = penta(P),
        storepenta(P+1, Target, dict:store(I, true, D))
    end.

check_pair(I,J,D) -> dict:is_key(I+J,D) andalso dict:is_key(J-I, D).

penta(N) -> trunc(N*(3*N-1)/2).


