"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting
with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values do not exceed four million, find
    the sum of the even-valued terms.
"""

def fib(n, cache = {}):
    if n not in cache:
        if n == 1: cache[n] = 1
        elif n == 2: cache[n] = 2
        else: cache[n]=fib(n-1) + fib(n-2)
    return cache[n]

l = []
s,f = 1,0
while f <= 4000000:
    f = fib(s)
    if f % 2 == 0: l.append(f)
    s+=1

print(sum(l))
